### ISSUE TITLE
Open CodeBox in Emulator

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#106]
**Description:**
This feature will allow code in the Docs Library to be opened up and run in the Emulator Page by pressing a button.

**To-Do List**

- [ ] Create API Post Method that accepts a body of code
- [ ] Create Dynamic View Return that prepopulates the code from the CodeMirror box into the Emulator.

**Definition of Done**

1. Passes all old Integration Testing
2. Needs some Selenium Based Testing

**Screenshots (optional)**
Below each Code Box would be this button
![image](https://user-images.githubusercontent.com/31376573/95001812-50896100-0582-11eb-8304-bb46882e0599.png)

This button would launch the Emulator with the code in the box.
![image](https://user-images.githubusercontent.com/31376573/95001836-ac53ea00-0582-11eb-982c-85ec138f306e.png)

**Comment by lubeskih** [comment]
Hey @rbaker26, I'd like to take this task.

I was looking around the code and was thinking of possible solutions apart from the one written. As the main problem here is how do we transport the data from one page to another, I thought of few possible solutions to think about, I personally like the second one:

1. Use `local storage`
2. Transport by GET request.

### local storage (not a fan)
1. User clicks on "Open in Emulator"
2. Copy contents of CodeMirror and encode to b64 (or another format).
3. Save the contents of the CodeMirror to localStorage
4. Redirect user to Emulator page
5. Anything in local storage (check for a specific key)? If so, write to the CodeMirror and remove the key, otherwise do nothing.

### Transport by GET request

Transporting by GET request where the encoded code from the mirror is part of the URL might be the most efficient way to tackle this problem.

1. User clicks on "Open in Emulator"
2. Copy contents of CodeMirror and encode to b64 (or another format).
3. Redirect the user to `https://sap1emu.net/Home/Emulator?code=<encoded_b64>`
4. The view expects an **optional** flag "code", if the flag exists, try to decode the contents and render the contents into the CodeMirror, if decoding fails or the value for the flag is empty, render it clean

This is good also because if later we to implement a "share code" feature, users can send an URL with the encoded code to other users, and those users will automatically have the code from the first user written in the CodeMirror.

The [TypeScript playground](https://www.typescriptlang.org/play?#code/BIUQMmDyAEBiBKkCy0AqpoFV5gITQC4BKIA) works in the very same way! :)

**Comment by rbaker26** [comment]
Since you also have to pass the InstructionSet string, a HTTPPost() might be a better option.
On local storage, I agree that is not a great option.  
Since this is hosted in a Azure Container, we really don't have any local storage.
We do have a Azure MSSQL Server, but that would be pretty slow.
